### ISSUE TITLE
FE revise and resubmit button for editing

### ISSUE THREAD

**Issue by qwaym0618** [NJIT-CLASS/frontend#29]
Create buttons for edit 
-button for approval
-button to return to the user to revise

2 APIs are created to handle that, just need to implement the buttons inside the edit task and consolidation of the editing task. Otherwise the system should handle everything normally and resetting the original task 'started' if the editor decides to return for revise. In addition, approval for the editing should directly lead to the triggering of the rest of the tasks in the original task

**Comment by alanRom** [comment]
Buttons will show up in reflection task and approval will appear for all Edit tasks
