### ISSUE TITLE
Assignment Editor: not using display labels in all tasks

### ISSUE THREAD

**Issue by profbieber** [NJIT-CLASS/frontend#37]
In the assignment editor, adding an assessment to a problem does not use the display names in all of the additional task types.  The display name is added to the grade task, but not the consolidate, dispute or resolve dispute tasks.

![image](https://user-images.githubusercontent.com/1903721/28434913-236bdfa4-6d5f-11e7-8719-bd76acde6123.png)

**Comment by alanRom** [comment]
Made it so consolidate, dispute, and resolve dispute task compute new names like all other tasks
