### ISSUE TITLE
task pages (execution mode): collapse other tasks, identify task to do

### ISSUE THREAD

**Issue by profbieber** [NJIT-CLASS/frontend#39]
When you see the task page, it should be clear which task you should work on.  Here are some ideas:

- The other task instances in the workflow instance should be collapsed, with just their task display types; and then the user can expand and re-collapse these.

- The task instance you are supposed to work on should be highlighted or marked in some way - maybe surrounded by an outline rectangle.   (That way you can find it again easily if you scroll away or collapse it.)

-  Perhaps scroll down to the task instance you should work on when the page is opened.

- “Task Page” at the top should be replaced with something like “Your task: [Task Display Name]” to remind the user of the task in the page.

Other ideas are welcome.

**Comment by alanRom** [comment]
Made all tasks, except the one you're working, collapsed by default and active task open.
