### ISSUE TITLE
No confirmation message on solve problem; 

### ISSUE THREAD

**Issue by profbieber** [NJIT-CLASS/frontend#45]
I clicked on submit in this solve problem, but no confirmation message appeared at the top of the screen.

![image](https://user-images.githubusercontent.com/1903721/28639039-bc216480-7214-11e7-831e-87835522638b.png)

**Comment by profbieber** [comment]
Also none on the grading task.

Maybe this is because I was trying this in Internet Explorer instead of Chrome???

**Comment by ar629** [comment]
When I either approved or rejected the comment task, there was no confirmation.

**Comment by alanRom** [comment]
Added more messages when submitting. Also, when successfully submitting, the page should now redirect you to the dashboard.
