### ISSUE TITLE
Dispute Task not visible in completed task page

### ISSUE THREAD

**Issue by profbieber** [NJIT-CLASS/frontend#49]
In http://pla.njit.edu:4001/task/88 which is a Dispute of Grade Create Problem there is no content for that task instance.  (The prior task instances in the page have content.)

So if it has content, that content is not showing.   If there was no dispute, then this should also be indicated in some way.    Thanks!

**Comment by alanRom** [comment]
Added a label that says "This dispute has been bypassed" (can be changed later).
