### ISSUE TITLE
Cursor confusing on task page

### ISSUE THREAD

**Issue by profbieber** [NJIT-CLASS/frontend#50]
The cursor shape is unclear on the task page.   

1. Normally the cursor should be an arrow if it is not hovering over anything where the user should be able to do something.   But the default shape now is a text entry cursor shape.
2. The cursor doesn't change when you hover over a collapsable section (such as Create Problem when there are subsequent sections) to show that you can click on the header to collapse or show a particular section.  So the user would not know that collapsing is an option.
3. The cursor changes to a hand over an input field, which is not the normal shape to show that you can type in that field.  That is when it should change to a text entry cursor shape.

**Comment by profbieber** [comment]
This issue was prompted by a comment from Saurabh, who adds: "it may create confusion about which fields are just text and which are actual links."   So maybe what can be clicked on (collapsable/expanded and fields with other actions should have an icon or be written in a different style to connote that they are different.

**Comment by alanRom** [comment]
I made the cursor change icon as suggested above. For clickable actions, it will show the hand. For text, it will be the text cursor. For empty space, it should be the regular mouse pointer.
